# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iF815QCEpXdfkhfDqWc39F9UiHxyfRgM
"""

list1 = [1, 2, 3, 4, 5]

list2 = [6, 7, 8, 9, 10]

result = map(lambda x, y: x + y, list1, list2)

# создание списка чисел от 1 до 100

numbers = list(range(1, 101))



# использование filter и lambda для поиска чисел, кратных 19 или 13

result = list(filter(lambda x: x % 19 == 0 or x % 13 == 0, numbers))



# вывод результата

print(result)

from functools import reduce



numbers = [4, 8, 2, 9, 5, 1, 6, 3, 7]



def find_max(x, y):

    return x if x > y else y



max_element = reduce(find_max, numbers)



print("Наибольший элемент:", max_element)